-- MySQL Script generated by MySQL Workbench
-- 06/09/20 11:00:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema citas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema citas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `citas` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `citas` ;

-- -----------------------------------------------------
-- Table `citas`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas`.`pacientes` (
  `PacIdentificacion` CHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `PacNombres` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `PacApellidos` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `PacFechaNacimiento` DATE NOT NULL COMMENT '',
  `PacSexo` ENUM('M','F') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`PacIdentificacion`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `citas`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas`.`medicos` (
  `MedIdentificacion` CHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `MedNombres` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `MedApellidos` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`MedIdentificacion`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `citas`.`consultorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas`.`consultorios` (
  `ConNumero` INT(3) NOT NULL COMMENT '',
  `ConNombre` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`ConNumero`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `citas`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas`.`citas` (
  `CitNumero` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `CitFecha` DATE NOT NULL COMMENT '',
  `CitHora` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `CitPaciente` CHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `CitMedico` CHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `CitConsultorio` INT(3) NOT NULL COMMENT '',
  `CitEstado` ENUM('Asignada','Cumplida','Solicitada','Cancelada') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT 'Asignada' COMMENT '',
  `CitObservaciones` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`CitNumero`)  COMMENT '',
  INDEX `CitPaciente` (`CitPaciente` ASC)  COMMENT '',
  INDEX `CitMedico` (`CitMedico` ASC)  COMMENT '',
  INDEX `CitConsultorio` (`CitConsultorio` ASC)  COMMENT '',
  CONSTRAINT `citas_ibfk_1`
    FOREIGN KEY (`CitPaciente`)
    REFERENCES `citas`.`pacientes` (`PacIdentificacion`),
  CONSTRAINT `citas_ibfk_2`
    FOREIGN KEY (`CitMedico`)
    REFERENCES `citas`.`medicos` (`MedIdentificacion`),
  CONSTRAINT `citas_ibfk_3`
    FOREIGN KEY (`CitConsultorio`)
    REFERENCES `citas`.`consultorios` (`ConNumero`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `citas`.`tratamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citas`.`tratamientos` (
  `TraNumero` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `TraFechaAsignado` DATE NOT NULL COMMENT '',
  `TraDescripcion` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `TraFechaInicio` DATE NOT NULL COMMENT '',
  `TraFechaFin` DATE NOT NULL COMMENT '',
  `TraObservaciones` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `TraPaciente` CHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`TraNumero`)  COMMENT '',
  INDEX `TraPaciente` (`TraPaciente` ASC)  COMMENT '',
  CONSTRAINT `Tratamientos_ibfk_1`
    FOREIGN KEY (`TraPaciente`)
    REFERENCES `citas`.`pacientes` (`PacIdentificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
